// Generated by https://quicktype.io

export interface IPipedriveActivityType {
    id:             number;
    order_nr:       number;
    name:           string;
    key_string:     string;
    icon_key:       string;
    active_flag:    boolean;
    color:          null;
    is_custom_flag: boolean;
    add_time:       string;
    update_time:    null;
}
